#!/usr/bin/python
import sys
import os
import shlex
import subprocess
command = shlex.split("env -i bash -c 'set -a && source ~/Wildcard/wildcard.conf && env'")
proc = subprocess.Popen(command, stdout = subprocess.PIPE)
for line in proc.stdout:
  (key, _, value) = line.partition("=")
  os.environ[key] = value
proc.communicate()
args = sys.argv
args[1] = os.path.expanduser("~/Wildcard/scripts/" + args[1])
os.execve(args[1], args[1:], os.environ)
